import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => fs.readFileSync(path.join(root, "public", file), "utf8");
const source = read("add-model-sheet.js");
const module = { exports: {} };
new Function("module", "exports", source)(module, module.exports);
const Sheet = module.exports;

assert.deepEqual(Sheet.PROVIDERS.map((provider) => provider.id), ["deepseek", "gemini", "qwen"]);
assert.deepEqual(Sheet.compatibleModels("deepseek", ["deepseek-v4-flash", "deepseek-v4-flash-vision-exp"]).map((model) => model.id), ["deepseek-v4-flash-vision-exp"]);
assert.deepEqual(Sheet.compatibleModels("gemini", ["gemini-3.7-flash", "gemini-3.1-flash-lite"]).map((model) => model.id), ["gemini-3.7-flash"]);
assert.deepEqual(Sheet.compatibleModels("qwen", ["qwen3.8-max", "qwen3.8-text"]).map((model) => model.id), ["qwen3.8-max"]);
assert.deepEqual(Sheet.compatibleModels("unknown", ["anything"]), []);
assert.match(source, /api\/runtime-providers\/qwen\/connection-check/);
assert.match(source, /正在发送模型列表请求/);
assert.match(source, /正在等待 Qwen 响应/);
assert.match(source, /正在验证图文输入能力/);
assert.match(source, /localStorage/);
assert.match(source, /job-radar-provider-api-key:/);
assert.match(source, /function persistCurrentKey/);
assert.match(source, /addEventListener\("blur", persistCurrentKey\)/);
assert.match(source, /JobRadarFloatingWindow\?\.mount\(byId\("panel"\)/);
assert.match(source, /dragHandle: byId\("panel"\)\.querySelector\("\.add-model-header"\)/);
assert.match(source, /function completeSelectedModel/);
assert.match(source, /completionTimer = window\.setTimeout/);
assert.match(source, /\}, 360\)/);
assert.match(source, /classList\.add\("is-closing"\)/);
assert.match(source, /classList\.add\("is-close-ready"\)/);
assert.match(source, /void byId\("panel"\)\.offsetWidth/);
assert.match(source, /closingAnimation = panel\.animate/);
assert.match(source, /\], \{ duration: 400, easing: "cubic-bezier\(\.16,1,\.3,1\)"/);
assert.match(source, /function setPanelOrigin/);
assert.match(source, /const clamp = \(value, minimum, maximum\)/);
assert.match(source, /--add-model-origin-scale/);
assert.doesNotMatch(source, /--add-model-origin-scale-x|--add-model-origin-scale-y/);
assert.match(source, /typeof onReturn === "function"/);
assert.doesNotMatch(source, /AWAITING_APPROVAL|indexedDB/);

const html = read("index.html"); const runtime = read("runtime-selection.js"); const css = read("styles.css");
assert.match(html, /id="add-model-sheet"/); assert.match(html, /id="add-model-close"/); assert.doesNotMatch(html, /id="add-model-complete"/);
assert.doesNotMatch(html, /id="add-model-close"[^>]*>×</);
assert.doesNotMatch(html, /id="add-model-drag-handle"/); assert.match(html, /id="add-model-provider"/);
assert.match(html, /class="add-model-provider-trigger"/); assert.match(html, /id="add-model-provider-menu"/); assert.match(html, /data-provider-id="deepseek"/); assert.match(html, /data-provider-id="gemini"/); assert.match(html, /data-provider-id="qwen"/);
assert.match(html, /class="add-model-footer"/); assert.match(html, /class="add-model-bin-top"/); assert.match(html, /class="add-model-bin-bottom"/);
assert.match(html, /API Key 保存在本地浏览器，不会上传到 Ariadne 云端/);
assert.match(html, /id="add-model-key-link"[^>]*target="_blank"[^>]*rel="noreferrer"/);
assert.match(source, /byId\("key-link"\)\.href = selectedProvider\?\.apiKeyUrl \|\| "#"/);
assert.match(source, /byId\("key-link"\)\.textContent = selectedProvider \? `获取 \$\{selectedProvider\.name\} API Key` : ""/);
assert.doesNotMatch(source, /获取 \$\{selectedProvider\.name\} API Key ↗/);
assert.match(css, /\.add-model-key-link \{[^}]*color: #1f2129[^}]*cursor: pointer[^}]*opacity: \.82[^}]*text-decoration: none/s);
assert.match(css, /\.add-model-key-link:hover, \.add-model-key-link:focus-visible \{[^}]*opacity: 1[^}]*text-decoration: underline/s);
assert.doesNotMatch(css, /\.add-model-key-link \{[^}]*#2961db/s);
assert.match(css, /\.runtime-back-link, \.runtime-guide-links a, \.runtime-guide-page a \{ color: #2961db/s);
assert.match(html, /add-model-connect-loader/); assert.match(html, /add-model-connect-check/);
assert.match(html, /删除已保存的 API Key/);
assert.doesNotMatch(html, /✓ 完成|仅本次使用|provider-picker/);
assert.doesNotMatch(html, /Qwen 业务空间 ID/);
assert.match(runtime, /JobRadarAddModelSheet\.mount/); assert.doesNotMatch(runtime, /local-first\.html#deepseek-key/);
assert.match(runtime, /const returnRect = byId\("runtime-selector"\)\.getBoundingClientRect\(\)/);
assert.match(runtime, /addModelSheet\.open\(originRect, returnRect\)/);
assert.match(css, /\.add-model-clear[^}]*transform 180ms/s);
assert.match(css, /\.add-model-clear:active[^}]*scale\(\.9\)/s);
assert.match(css, /\.add-model-connect[^}]*transform 180ms/s);
assert.match(css, /\.add-model-connect:not\(:disabled\):active[^}]*scale\(\.985\)/s);
assert.match(css, /\.add-model-provider-trigger\[aria-expanded="true"\] svg[^}]*rotate\(180deg\)/s);
assert.match(css, /@keyframes add-model-float-expand/);
assert.match(css, /\.add-model-panel\.is-close-ready \{ animation: none; \}/);
assert.match(css, /add-model-float-expand 430ms cubic-bezier\(\.16,1,\.3,1\)/);
assert.match(css, /\.add-model-panel \{[^}]*top: 50%/s);
assert.match(css, /\.add-model-panel \{[^}]*border-radius: 26px/s);
assert.match(css, /\.add-model-sheet\.is-closing \.add-model-panel[^}]*pointer-events: none/s);
assert.match(css, /\.floating-resize-handle\[data-direction="ne"\]/);
assert.match(css, /\.add-model-bin \{[^}]*height: 19px[^}]*width: 18px/s);
assert.doesNotMatch(css, /@keyframes sheet-up|\.add-model-drag-handle/);
assert.match(css, /\.sheet-icon-button \{[^}]*background: transparent/s);
assert.match(css, /\.sheet-icon-button::before \{[^}]*height: 24px[^}]*width: 24px/s);
assert.doesNotMatch(css, /\.sheet-icon-button \{[^}]*border-radius: 50%/s);
assert.doesNotMatch(css, /\.sheet-icon-button \{[^}]*box-shadow/s);
console.log("add_model_sheet_contract=pass");
