import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = fs.readFileSync(path.join(root, "public", "ascii-waves.js"), "utf8");

assert.match(source, /#runtime-ascii-waves/);
assert.match(source, /requestAnimationFrame/);
assert.match(source, /getContext\("2d"/);
assert.match(source, /pointermove/);
assert.match(source, /pointerTarget/);
assert.match(source, /const glyphs = "cyslap"/);
assert.doesNotMatch(source, /blankAmount|openRipple|rippleSet|smoothstep/);
assert.match(source, /pointerTarget\.energy \*= \.8/);
assert.match(source, /Math\.max\(\.35, movement \/ 4\)/);
assert.match(source, /context\.globalAlpha = opacity/);
assert.match(source, /pointer\.vx \* push/);
assert.match(source, /const localWake =/);
assert.match(source, /const influence = Math\.exp\(-distanceSquared \/ 19000\)/);
assert.match(source, /const push = influence \* 184/);
assert.match(source, /const pointerActive =/);
assert.match(source, /let cellWidth = 8\.16/);
assert.match(source, /let cellHeight = 9\.52/);
assert.match(source, /const frameInterval = pointerTarget\.energy > \.01 \|\| pointer\.energy > \.01 \? 32 : 48/);
assert.match(source, /flowClock \+= elapsed \* motionSpeed/);
assert.match(source, /const motionTime = flowClock/);
assert.match(source, /pointer\.energy \+= \(pointerTarget\.energy - pointer\.energy\) \* \.82/);
assert.match(source, /Math\.tanh\(offsetX \/ 28\) \* cellWidth \* 1\.6/);
assert.match(source, /const localContrast = \(density - \.5\) \* \.1/);
assert.doesNotMatch(source, /interactionTone/);
assert.match(source, /const LOCKED_BACKGROUND_SETTINGS = Object\.freeze/);
assert.match(source, /opacity: \.77/);
assert.match(source, /fontSize: 6\.8/);
assert.match(source, /density: 1\.1/);
assert.match(source, /speed: 2\.8/);
assert.match(source, /direction: 65/);
assert.match(source, /twist: 2/);
assert.match(source, /tension: \.4/);
assert.match(source, /canvas\.style\.opacity = String\(backgroundSettings\.opacity\)/);
assert.match(source, /const rawCellWidth = Math\.max\(2\.6, fontSize \* 1\.2 \/ characterDensity\)/);
assert.match(source, /canvas\.dataset\.flowSpeed = motionSpeed\.toFixed\(1\)/);
assert.match(source, /const IS_DEVELOPMENT_HOST = window\.location\.hostname === "127\.0\.0\.1" \|\| window\.location\.hostname === "localhost"/);
assert.match(source, /const DEV_SETTINGS_KEY = "job-radar\.ascii-dev-tuner\.v3"/);
assert.match(source, /const LEGACY_SETTINGS_KEYS = \["job-radar\.ascii-dev-tuner\.v2", "job-radar\.ascii-tuner\.v1"\]/);
assert.match(source, /function loadDevelopmentSettings\(\)/);
assert.match(source, /function installDeveloperTuner\(\)/);
assert.match(source, /if \(!IS_DEVELOPMENT_HOST\) return/);
assert.match(source, /localStorage\.setItem\(DEV_SETTINGS_KEY, JSON\.stringify\(backgroundSettings\)\)/);
assert.match(source, /\{ key: "twist", label: "扭曲 Twist"/);
assert.match(source, /\{ key: "twist", label: "扭曲 Twist", min: 0, max: 2/);
assert.match(source, /legacy \? normalizedSettings\(\{ \.\.\.JSON\.parse\(legacy\), twist: 2 \}\)/);
assert.match(source, /const localTwist = waveTwist/);
assert.match(source, /let tensionScale = \.72 \+ backgroundSettings\.tension \* \.56/);
assert.match(source, /let directionAngle = backgroundSettings\.direction \* Math\.PI \/ 180/);
assert.match(source, /canvas\.dataset\.density/);
assert.match(source, /canvas\.dataset\.flowDirection/);
assert.match(source, /canvas\.dataset\.waveTwist/);
assert.match(source, /canvas\.dataset\.waveTension/);
assert.match(source, /context\.font = `\$\{fontSize\}px/);
assert.match(source, /document\.hidden/);
assert.match(source, /visibilitychange/);
assert.match(source, /estimatedCells > backgroundSettings\.maxCells/);
assert.match(source, /canvas\.dataset\.cellCount/);
assert.match(source, /pointer\.energy = \.7/);
assert.match(source, /pointerTarget\.energy = \.85/);
assert.match(source, /pointer\.energy = Math\.max\(pointer\.energy, eventEnergy \* \.9\)/);
assert.doesNotMatch(source, /Math\.sin\(distance/);
assert.match(source, /fillText\(glyph, drawX, drawY\)/);
assert.match(source, /const overscanX = cellWidth \* 4/);
assert.match(source, /const overscanY = cellHeight \* 4/);
assert.match(source, /for \(let y = -overscanY; y < height \+ overscanY/);
assert.match(source, /paused-for-navigation/);
assert.match(source, /prefers-reduced-motion/);
assert.doesNotMatch(source, /fetch\(|https?:\/\//);
console.log("ascii_waves_contract=pass");
