import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const UI = createRequire(import.meta.url)('../public/conversation-ui-domain.js');
const listeners = new Set();
const input = { value: '发送的原文', addEventListener(_name, fn) { listeners.add(fn); }, removeEventListener(_name, fn) { listeners.delete(fn); } };
let draft = UI.takeDraft(input);
assert.equal(input.value, '', 'clear synchronously before waiting for a response');
assert.equal(draft.text, '发送的原文');
input.value = '等待期间的新草稿';
draft.finish();
assert.equal(input.value, '等待期间的新草稿', 'success must not clear the next draft');
draft = UI.takeDraft(input);
draft.finish(true);
assert.equal(input.value, '等待期间的新草稿', 'restore untouched draft on failure');
draft = UI.takeDraft(input);
input.value = '新内容';
draft.finish(true);
assert.equal(input.value, '新内容', 'failure must not overwrite a newer draft');
draft = UI.takeDraft(input);
listeners.forEach(fn => fn());
input.value = '';
draft.finish(true);
assert.equal(input.value, '', 'an intentionally cleared newer draft stays empty');
assert.equal(listeners.size, 0);
console.log('draft capture: immediate clear, success, failure and newer-input boundaries PASS');
