import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const require=createRequire(import.meta.url);
const Applications=require('../public/job-application-domain.js');
const initial=Applications.initial('canonical-job-stable-1');
assert.equal(initial.stage,'NOT_APPLIED');
let state=initial;
for(const stage of ['APPLIED','IN_PROGRESS','CLOSED']) state=Applications.next(state,{stage,outcome:stage==='CLOSED'?'RESUME_REJECTED':'',note:'用户填写'},state.revision);
assert.equal(state.history.length,3);
assert.equal(state.outcome,'RESUME_REJECTED');
assert.equal(Applications.matches(state,'ACTIVE'),false);
assert.equal(Applications.matches(state,'CLOSED'),true);
assert.equal(Applications.matches(state,'ALL'),true);
assert.equal(initial.revision,0,'updates do not mutate original records');
assert.throws(()=>Applications.next(state,{stage:'APPLIED',outcome:'',note:''},1),/其他页面/);
for(const change of [{stage:'UNKNOWN',outcome:'',note:''},{stage:'APPLIED',outcome:'RESUME_REJECTED',note:''},{stage:'CLOSED',outcome:'invented',note:''},{stage:'CLOSED',outcome:'',note:'字'.repeat(301)}]) assert.throws(()=>Applications.next(state,change,state.revision));
const reopened=Applications.next(state,{stage:'IN_PROGRESS',outcome:'',note:''},state.revision);
assert.equal(reopened.outcome,'');
assert.equal(reopened.history[2].outcome,'RESUME_REJECTED','reopening preserves past result');
assert.equal(reopened.job_context_id,initial.job_context_id);
assert.equal(Applications.matches(reopened,'ACTIVE'),true);
assert.equal(Applications.initial('second-job').revision,0);
assert.throws(()=>Applications.validate({...state,stage:'corrupt'}),/无法读取/);
const library=readFileSync(new URL('../public/jd.html',import.meta.url),'utf8');
const detail=readFileSync(new URL('../public/job-detail.html',import.meta.url),'utf8');
const pages=readFileSync(new URL('../public/v1-pages.js',import.meta.url),'utf8');
assert.doesNotMatch(library,/job-stage-dialog|job-stage-note/,'no separate stage dialog or notes editor in the library');
assert.match(detail,/id="job-application-form"/);
assert.match(detail,/job-application-domain\.js/);
assert.match(pages,/const filters = \{ ACTIVE: "关注中", CLOSED: "已结束", ALL: "全部" \}/);
assert.match(pages,/\$\{card\}<button type="button" class="runtime-selector v1-job-stage-select"/,'interactive dropdown is outside the card link');
assert.match(library,/job-stage-menu\.js/);
assert.match(pages,/Number\(select\.dataset\.revision\)/,'one-click save still checks the observed revision');
const notesOnly=Applications.next(state,{stage:state.stage,outcome:'INTERVIEW_REJECTED',note:'更新反馈'},state.revision);
assert.equal(notesOnly.stage,state.stage);
assert.equal(notesOnly.history.at(-2).outcome,'RESUME_REJECTED');
console.log('job_application_transitions_history_filter_validation_conflicts=PASS');
