import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const Applications=require('../public/job-application-domain.js');
const initial=Applications.initial('canonical-job-stable-1');
assert.equal(initial.stage,'NOT_APPLIED');
let state=initial;
for(const stage of ['APPLIED','IN_PROGRESS','CLOSED']) state=Applications.next(state,{stage,outcome:stage==='CLOSED'?'RESUME_REJECTED':'',note:'用户填写'},state.revision);
assert.equal(state.history.length,3);
assert.equal(state.outcome,'RESUME_REJECTED');
assert.equal(Applications.matches(state,'ACTIVE'),false);
assert.equal(Applications.matches(state,'CLOSED'),true);
assert.equal(Applications.matches(state,'ALL'),true);
assert.equal(initial.revision,0,'updates do not mutate original records');
assert.throws(()=>Applications.next(state,{stage:'APPLIED',outcome:'',note:''},1),/其他页面/);
for(const change of [{stage:'UNKNOWN',outcome:'',note:''},{stage:'APPLIED',outcome:'RESUME_REJECTED',note:''},{stage:'CLOSED',outcome:'invented',note:''},{stage:'CLOSED',outcome:'',note:'字'.repeat(301)}]) assert.throws(()=>Applications.next(state,change,state.revision));
const reopened=Applications.next(state,{stage:'IN_PROGRESS',outcome:'',note:''},state.revision);
assert.equal(reopened.outcome,'');
assert.equal(reopened.history[2].outcome,'RESUME_REJECTED','reopening preserves past result');
assert.equal(reopened.job_context_id,initial.job_context_id);
assert.equal(Applications.matches(reopened,'ACTIVE'),true);
assert.equal(Applications.initial('second-job').revision,0);
assert.throws(()=>Applications.validate({...state,stage:'corrupt'}),/无法读取/);
console.log('job_application_transitions_history_filter_validation_conflicts=PASS');
