import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/v1-pages.js',import.meta.url),'utf8');
const helper=source.slice(source.indexOf('  let pageFadeTimer = null;'),source.indexOf('  function installDetailCardOverlay()'));
const pending=new Map(),classes=new Set(),visits=[],animationWrites=[];
let reduced=false,serial=0,removedRoutes=0;
const style={set animation(value){animationWrites.push(value)}};
const context=vm.createContext({URL,window:{location:{href:'http://127.0.0.1:8000/personal-information.html',origin:'http://127.0.0.1:8000',pathname:'/personal-information.html',search:'',assign:url=>visits.push(url)},matchMedia:()=>({matches:reduced}),setTimeout(fn,delay){assert.equal(delay,320);pending.set(++serial,fn);return serial},clearTimeout:id=>pending.delete(id)},document:{body:{classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)}},querySelector:()=>({style,offsetWidth:800})},safeSession:{remove(){removedRoutes++}},transitionSourceSelector:'.v1-candidate-card, .v1-add-guide-card'});
vm.runInContext(helper+';this.api={pageFadeDestination,navigateWithPageFade,restorePageFade};',context);
const {pageFadeDestination,navigateWithPageFade,restorePageFade}=context.api;
const link=(href,extra={})=>({getAttribute:name=>name==='href'?href:extra[name]??null,hasAttribute:name=>Object.hasOwn(extra,name),matches:()=>Boolean(extra.card)});
for(const href of ['/personal-understanding.html','/job-overview.html','/jd.html','/workspace.html','/','/job-detail.html?job=sample#details']) assert.ok(pageFadeDestination(link(href))?.startsWith('http://127.0.0.1:8000/'));
for(const anchor of [null,link('#top'),link('/personal-information.html'),link('https://example.com/other.html'),link('/file.pdf'),link('mailto:test@example.com'),link('http://['),link('/job-overview.html',{download:''}),link('/job-overview.html',{target:'_blank'}),link('/candidate-detail.html',{card:true})]) assert.equal(pageFadeDestination(anchor),null);
assert.ok(pageFadeDestination(link('/job-overview.html',{target:'_self'})));
navigateWithPageFade('/personal-understanding.html');navigateWithPageFade('/job-overview.html');
assert.equal(pending.size,1,'rapid repeated activation schedules only one navigation');assert.ok(classes.has('v1-route-leaving'));assert.equal(removedRoutes,1);assert.equal(visits.length,0);
[...pending.values()][0]();assert.deepEqual(visits,['/personal-understanding.html']);
restorePageFade({persisted:true});assert.equal(pending.size,0);assert.equal(classes.size,0);assert.deepEqual(animationWrites,['none','']);
reduced=true;navigateWithPageFade('/job-overview.html');assert.deepEqual(visits,['/personal-understanding.html','/job-overview.html']);assert.equal(pending.size,0);assert.equal(classes.size,0);
console.log('Page navigation: internal links, exclusions, single navigation, reduced motion and cached-page restoration PASS');
