import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => fs.readFileSync(path.join(root, "public", file), "utf8");
const html = read("index.html");
const geminiConnect = read("gemini-connect.html");
const geminiGuide = read("gemini-api-key-guide.html");
const script = read("runtime-selection.js");
const css = read("styles.css");

assert.match(html, /ONE|runtime-selector/);
assert.match(html, /添加新的模型/);
assert.match(html, /add-model-sheet\.js/);
assert.match(html, /runtime-selection\.js\?v=runtime-ui-v48/);
assert.match(html, /id="runtime-action-symbol"[^>]*><svg viewBox="0 0 24 24"><path d="M9 5\.5 15\.5 12 9 18\.5"/);
assert.match(html, /class="runtime-chevron"[^>]*><svg viewBox="0 0 24 24"><path d="M5\.5 9 12 15\.5 18\.5 9"/);
assert.doesNotMatch(html, /id="runtime-action-symbol"[^>]*>→/);
assert.doesNotMatch(script, /symbol\.textContent/);
for (const runtimeBackPage of [geminiConnect, geminiGuide]) {
  assert.match(runtimeBackPage, /class="runtime-back-link"[^>]*><span class="runtime-back-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M15 5\.5 8\.5 12 15 18\.5"/);
  assert.doesNotMatch(runtimeBackPage, /← 返回/);
}
assert.doesNotMatch([html, geminiConnect, geminiGuide].join(""), /M5 12h14|M19 12H5/);
assert.match(html, /floating-window\.js\?v=runtime-ui-v48/);
assert.doesNotMatch(html, /<p class="runtime-step">选择运行方式<\/p>/);
assert.doesNotMatch(html, /01&nbsp;&nbsp;选择运行方式/);
assert.match(html, /本地运行/);
assert.match(html, /Content-Security-Policy/);
assert.match(script, /phase: "IDLE"/);
assert.match(script, /"CHECKING"/);
assert.match(script, /"READY"/);
assert.match(script, /"FAILED"/);
assert.match(script, /"LOCAL_READY"/);
assert.match(script, /api\/runtime-check/);
assert.doesNotMatch(script, /Gemini · 图文模型|gemini-connect\.html|runtime-gemini-model/);
assert.match(script, /restoreGeminiReadyState/);
assert.match(script, /sessionStorage\.setItem\("job-radar-runtime-check"/);
assert.match(script, /career_data_sent: false/);
assert.match(script, /multimodal_connection_ready/);
assert.match(script, /selectOfficialMultimodalModel/);
assert.match(script, /"OFFICIAL_READY"/);
assert.match(script, /"OFFICIAL_MODEL_CAPABILITY"/);
assert.match(script, /JobRadarAddModelSheet\.mount/);
assert.match(script, /job-radar-added-runtime-models/);
assert.match(script, /job-radar-selected-runtime/);
assert.match(script, /window\.location\.hostname === "localhost"/);
assert.match(script, /canonicalUrl\.hostname = "127\.0\.0\.1"/);
assert.match(script, /writeLocalJson\(ADDED_MODELS_STORAGE_KEY/);
assert.match(script, /function applyReadyModel/);
assert.match(script, /const hasModels = selectableModels\(\)\.length > 0/);
assert.match(script, /hasModels \? "选择模型" : "选择运行方式"/);
const loadModelsSource = script.slice(script.indexOf("async function loadModels"), script.indexOf("function selectAddedMultimodalModel"));
assert.match(loadModelsSource, /const restoredModel = selectableModels\(\)\.find\(\(model\) => model\.provider_id === state\.provider && model\.model_id === state\.model\);[\s\S]*applyReadyModel\(restoredModel, false\)/);
assert.doesNotMatch(loadModelsSource, /defaultModel|runtime_default|persistSelectedRuntime/);
assert.match(script, /const ready = state\.phase === "READY" \|\| state\.phase === "OFFICIAL_READY" \|\| state\.phase === "LOCAL_READY"/);
assert.match(script, /if \(model\?\.provider_id === "deepseek" && model\.multimodal_readiness === "VERIFIED"\) selectOfficialMultimodalModel/);
assert.match(script, /menu\.classList\.add\("is-open"\)/);
assert.match(script, /selectAddedMultimodalModel/);
assert.match(script, /button\.dataset\.provider/);
assert.doesNotMatch(script, /Browser Direct BYOK|实验视觉模型；普通文本连接未确认|稳定文本模型/);
assert.doesNotMatch(html, /id="add-model-complete"|aria-label="完成"/);
assert.doesNotMatch(html, /✓ 完成/);
assert.doesNotMatch(script, /console\./);
assert.doesNotMatch(script, /\.innerHTML\s*=/);
assert.match(script, /navigateWithPageTransition\("\/workspace\.html", byId\("runtime-action"\)\)/);
assert.match(script, /runtime-page-leaving/);
assert.match(script, /job-radar-runtime-leave/);
assert.doesNotMatch(script, /runtime-entry-bloom/);
assert.match(script, /window\.setTimeout\(\(\) => window\.location\.assign\(destination\), 240\)/);
assert.match(css, /\.runtime-spinner/);
assert.match(css, /#runtime-action-symbol svg \{[^}]*stroke-linecap: round[^}]*stroke-linejoin: round[^}]*stroke-width: 2\.4/s);
assert.match(css, /\.runtime-chevron svg \{[^}]*stroke-linecap: round[^}]*stroke-linejoin: round[^}]*stroke-width: 2\.4/s);
assert.match(css, /\.runtime-back-icon svg \{[^}]*stroke-linecap: round[^}]*stroke-linejoin: round[^}]*stroke-width: 2\.4/s);
assert.match(css, /\.runtime-spinner svg \{ display: none; \}/);
assert.match(css, /\.runtime-selector \{[^}]*padding: 0 16px 0 20px/s);
assert.match(css, /\.runtime-menu \{[^}]*padding: 8px/s);
assert.match(css, /\.runtime-existing-model\[aria-selected="true"\]::after, #runtime-local\[aria-selected="true"\]::after \{[^}]*background: currentColor[^}]*color: #1f2129[^}]*content: ""[^}]*height: 20px[^}]*stroke-width='2\.6'[^}]*stroke-linecap='round'[^}]*stroke-linejoin='round'[^}]*20px 20px[^}]*right: 8px[^}]*width: 20px/s);
assert.doesNotMatch(css, /\.runtime-existing-model\[aria-selected="true"\]::after, #runtime-local\[aria-selected="true"\]::after \{[^}]*#2961db[^}]*content: "✓"/s);
assert.match(script, /button\.setAttribute\("aria-selected", String\(state\.mode === "ai"/);
assert.match(script, /byId\("runtime-local"\)\.setAttribute\("aria-selected", String\(state\.mode === "local"\)\)/);
assert.match(css, /\.runtime-menu\.is-open/);
assert.match(css, /\.runtime-menu \{[^}]*top: 68px/s);
assert.match(css, /\.runtime-action\.ready:hover[^}]*box-shadow/s);
assert.match(css, /\.runtime-action\.ready:active[^}]*transform: scale\(\.9\)/s);
assert.match(css, /\.runtime-selector\[aria-expanded="true"\] \.runtime-chevron[^}]*rotate\(180deg\)/s);
assert.match(html, /id="runtime-ascii-waves"/);
assert.match(html, /ascii-waves\.js\?v=runtime-ui-v48/);
assert.doesNotMatch(html, /ascii-tuner|ascii-opacity|ascii-font-size|ascii-flow-speed|ascii-density|ascii-flow-direction|ascii-wave-twist|ascii-wave-tension/);
assert.match(css, /\.ascii-tuner-panel\.is-open/);
assert.match(css, /\.runtime-page button:not\(:disabled\):active[^}]*scale: \.97/s);
assert.match(css, /\.runtime-page\.runtime-page-leaving[^}]*opacity: 0/s);
assert.match(css, /\.runtime-page \{[^}]*animation: v1-page-fade-in 420ms cubic-bezier\(\.22,\.78,\.24,1\)[^}]*opacity: 1[^}]*transition: opacity 240ms/s);
assert.match(css, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*\.runtime-page, \.v1-page-shell \{ animation: none; \}/);
assert.doesNotMatch(css, /@keyframes runtime-entry-bloom|\.runtime-entry-bloom/);
assert.match(css, /\.runtime-ascii-waves[^}]*opacity: 1/);
assert.match(css, /\.runtime-ascii-waves[^}]*height: 100vh[^}]*width: 100vw/);
assert.match(css, /\.runtime-page \{ background: #f9f9fa/s);
assert.match(css, /\.runtime-shell[^}]*justify-content: center[^}]*translateY\(-3vh\)/s);
assert.match(css, /\.sheet-icon-button[^}]*align-items: center[^}]*justify-content: center/s);
assert.match(css, /\.sheet-icon-button:active[^}]*scale\(\.82\)/s);
assert.match(script, /const originRect = byId\("runtime-add-model"\)\.getBoundingClientRect\(\)/);
assert.match(script, /addModelSheet\.open\(originRect, returnRect\)/);
assert.match(script, /\}, \(\) => openMenu\(\)\)/);
assert.doesNotMatch(html, /runtime-menu-label|id="runtime-menu" class="runtime-menu hidden"/);
console.log("runtime_selection_ui_contract=pass");
