"""Generate the VI resources from one reviewed manifest. No third-party packages."""
from pathlib import Path
import json, sys
ROOT = Path(__file__).resolve().parents[1]
def outputs():
    spec = json.loads((ROOT / 'public/vi/manifest.json').read_text())
    result = {'public/vi/tokens.css': '/* Generated by scripts/build_vi.py; edit vi/manifest.json. */\n:root {\n' + ''.join(f'  {t["name"]}: {t["value"]};\n' for t in spec['tokens']) + '}\n'}
    css = '/* Generated icon bindings. Geometry lives in vi/manifest.json. */\n.vi-icon { background: currentColor; display: inline-block; flex: 0 0 auto; height: var(--vi-icon-small); width: var(--vi-icon-small); vertical-align: middle; mask: var(--vi-icon-image) center / contain no-repeat; -webkit-mask: var(--vi-icon-image) center / contain no-repeat; }\n'
    for icon in spec['icons']:
        name = icon['name']
        result[f'public/vi/icons/{name}.svg'] = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="{icon["stroke"]}" stroke-linecap="round" stroke-linejoin="round">{icon["body"]}</svg>\n'
        css += f'.vi-icon[data-icon="{name}"] {{ --vi-icon-image: url("/vi/icons/{name}.svg"); }}\n'
    result['public/vi/icons.css'] = css
    return result
if __name__ == '__main__':
    check = '--check' in sys.argv
    failed = []
    for name, body in outputs().items():
        target = ROOT / name
        if check:
            if not target.exists() or target.read_text() != body: failed.append(name)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body)
    if failed: raise SystemExit('VI generated resources differ: ' + ', '.join(failed))
    print('VI generated resources: ' + ('PASS' if check else 'updated'))
