"""Export separate public Pages and Python Worker directories; never user state."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.build_web_release import release_files
from scripts.check_public_release import SECRET_PATTERN, FORBIDDEN_DIRS, PRIVATE_DATA_DIRS, SECRET_NAMES

EXTRA = {"src/runtime_transport.py", "src/browser_pdf_delivery.py", "public/browser-pdf-delivery.js",
         "public/cloudflare-preview.js", "public/cloudflare-preview.css"}
GITHUB = re.compile(r"https://github\.com/KAI-NEX/[A-Za-z0-9_.-]+/releases/download/[A-Za-z0-9_.-]+/(Ariadne-Local-macOS-arm64-[0-9-]+\.zip)")


def build(output, pdfjs, download_url=None):
    if json.loads((pdfjs / "package.json").read_text())["version"] != "5.4.624":
        raise ValueError("Expected reviewed pdfjs-dist 5.4.624")
    output.mkdir(parents=True, exist_ok=False)
    pages, worker = output / "pages", output / "api"
    pages.mkdir(); worker.mkdir()
    runtime = worker / "runtime"
    runtime.mkdir()
    for name in sorted(set(release_files()) | EXTRA):
        if not name.startswith(("src/", "public/", "data/")) and name not in {"app.py", "web_app.py"}:
            continue
        source = ROOT / name
        if (source.is_symlink() or set(Path(name).parts) & FORBIDDEN_DIRS or source.name in SECRET_NAMES
            or (name.startswith("data/") and set(Path(name).parts) & PRIVATE_DATA_DIRS)
            or SECRET_PATTERN.search(source.read_bytes())):
            raise ValueError("Unsafe export source: " + name)
        destinations = []
        if name.startswith("public/"):
            destinations.append(pages / name.removeprefix("public/"))
            if name.endswith((".json", ".pdf")) or name == "public/job-radar-multimodal-smoke.jpg":
                destinations.append(runtime / name)
        else:
            destinations.append(runtime / name)
        for target in destinations:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
    # Route contracts are generated by the same local handler, without keys,
    # provider discovery, database initialization or network access.
    from web_app import WebApplication, GET_PATHS
    application = WebApplication(["https://ariadne.kai-nex.com"])
    for path in sorted(GET_PATHS):
        if not path.endswith(".js"):
            continue
        code, _, chunks = application.dispatch({"PATH_INFO": path, "REQUEST_METHOD": "GET", "HTTP_HOST": "ariadne.kai-nex.com"})
        if code != 200:
            raise ValueError("Contract export failed: " + path)
        (pages / path.lstrip("/")).write_bytes(b"".join(chunks))
    # Export the application pages unchanged, without the former preview banner.
    (pages / "404.html").write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Ariadne · 页面不存在</title><p>页面不存在。<a href="/">返回 Ariadne</a></p></html>')
    vendor = pages / "vendor/pdfjs"
    vendor.mkdir(parents=True)
    for name in ("pdf.mjs", "pdf.worker.mjs"):
        shutil.copyfile(pdfjs / "build" / name, vendor / name)
    for name in ("cmaps", "standard_fonts", "wasm"):
        shutil.copytree(pdfjs / name, vendor / name)
    shutil.copyfile(pdfjs / "LICENSE", vendor / "LICENSE")
    shutil.copyfile(ROOT / "deploy/cloudflare/pages-worker.js", pages / "_worker.js")
    (pages / "_routes.json").write_text(json.dumps({"version": 1, "include": ["/api/*", "/healthz"], "exclude": []}))
    (pages / "_headers").write_text("/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  X-Frame-Options: SAMEORIGIN\n  Content-Security-Policy: frame-ancestors 'self'\n  Cache-Control: no-cache\n")
    shutil.copyfile(ROOT / "deploy/cloudflare/worker.py", runtime / "worker.py")
    for name in ("wrangler.jsonc", "pyproject.toml", "pylock.toml"):
        shutil.copyfile(ROOT / "deploy/cloudflare" / name, worker / name)
    (worker / "package.json").write_text(json.dumps({"private": True, "devDependencies": {"wrangler": "4.134.0"}}, indent=2))
    (output / "wrangler.jsonc").write_text(json.dumps({"name": "ariadne", "pages_build_output_dir": "pages", "compatibility_date": "2026-09-18", "services": [{"binding": "ARIADNE_API", "service": "ariadne-api"}]}, indent=2))
    shutil.copyfile(ROOT / "docs/current/CLOUDFLARE_DEPLOYMENT.md", output / "部署说明.md")
    downloads = pages / "downloads"
    downloads.mkdir(exist_ok=True)
    metadata = json.loads((ROOT / "public/downloads/latest.json").read_text())
    if download_url:
        match = GITHUB.fullmatch(download_url)
        archive = ROOT / "public" / metadata["url"].lstrip("/")
        if not match or match.group(1) != archive.name or archive.stat().st_size != metadata["bytes"] or hashlib.sha256(archive.read_bytes()).hexdigest() != metadata["sha256"]:
            raise ValueError("Download URL or local package hash does not match")
        metadata["url"] = download_url
        (downloads / "latest.json").write_text(json.dumps(metadata))
    else:
        (downloads / "latest.json").write_text(json.dumps({"available": False}))
    files = list(pages.rglob("*"))
    if sum(p.is_file() for p in files) > 1000 or any(p.is_file() and p.stat().st_size > 25 * 1024 * 1024 for p in files):
        raise ValueError("Cloudflare Pages upload limit exceeded")
    archive = output / "Ariadne-Pages.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
        for path in files:
            if path.is_file(): z.write(path, str(path.relative_to(pages)))
    manifest = {"created_at": datetime.now().isoformat(), "origin": "https://ariadne.kai-nex.com",
        "pages_archive_sha256": hashlib.sha256(archive.read_bytes()).hexdigest(), "local_download_configured": bool(download_url),
        "source_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "files": {str(p.relative_to(output)): hashlib.sha256(p.read_bytes()).hexdigest() for p in output.rglob("*") if p.is_file()},
        "deployed": False}
    (output / "release.json").write_text(json.dumps(manifest, indent=2))
    return {"directory": str(output), "pages_zip": str(archive), "pages_files": sum(p.is_file() for p in files),
        "download_configured": bool(download_url), "worker_directory": str(worker)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--pdfjs", type=Path, required=True, help="Installed pdfjs-dist 5.4.624 directory")
    parser.add_argument("--download-url", help="Published public GitHub Release URL matching the current local ZIP")
    args = parser.parse_args()
    output = args.output or ROOT / ".cache/cloudflare-distribution" / datetime.now().strftime("%Y%m%d-%H%M%S")
    print(json.dumps(build(output.resolve(), args.pdfjs.resolve(), args.download_url)))
